import type { Metadata } from "next";
import "./globals.css";
import { lato, openSans, ptSans, yanoneKaffeesatz } from "../lib/fonts";

export const metadata: Metadata = {
  title: "Veneza Chocolateria | Chocolates, Doces Finos, Trufas e muito mais...",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} ${yanoneKaffeesatz.variable} ${ptSans.variable} ${lato.variable} font-sans antialiased`}>
        {children}
        </body>
    </html>
  );
}
